language: minimal

jobs:
  include:
    - name: 'Retail'
      install:
        - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -d -z
        - wget -O tests/profession_api.lua https://raw.githubusercontent.com/Beast-Masters-addons/LibProfessions/master/tests/profession_api_retail.lua
      after_success:
        - cd $TRAVIS_BUILD_DIR
        - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

    - name: 'Classic'
      install:
        - export CLASSIC_VERSION="1.13.6"
        - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -d -z -g $CLASSIC_VERSION
        - wget -O tests/profession_api.lua https://raw.githubusercontent.com/Beast-Masters-addons/LibProfessions/master/tests/profession_api_classic.lua
      after_success:
        - cd $TRAVIS_BUILD_DIR
        - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g $CLASSIC_VERSION

addons:
  apt:
    packages:
      - luarocks

before_install:
  - sudo luarocks install luacheck
  - sudo luarocks install luaunit
  - sudo luarocks install luacov

before_script:
  - cp -r tests .release/ProfessionMailer
  - cd .release/ProfessionMailer

script:
  - luacheck addon --no-color -q --no-self
  - cd tests
  - lua -lluacov test_ProfessionData.lua
  - bash <(curl -s https://codecov.io/bash)